#!/bin/bash

echo "========================================="
echo "  如何查看 Cpolar 公网地址"
echo "========================================="
echo ""
echo "✅ Cpolar 正在运行（进程 ID: $(pgrep cpolar)）"
echo ""
echo "📋 查看公网地址的方法："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "方法 1：查看运行 cpolar 的终端窗口"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "在运行 'cpolar http 80' 的终端中，会显示："
echo ""
echo "  Forwarding    http://xxxxxx.cpolar.cn -> http://localhost:80"
echo "  Forwarding    https://xxxxxx.cpolar.cn -> http://localhost:80"
echo ""
echo "  ⬆️ 这两行就是你的公网访问地址！"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "方法 2：访问 Web 管理界面（推荐）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "在浏览器中打开："
echo ""
echo "  👉 http://127.0.0.1:9200"
echo ""
echo "在管理界面可以看到："
echo "  • 公网访问地址"
echo "  • 实时连接数"
echo "  • 访问日志"
echo "  • 流量统计"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "方法 3：登录 Cpolar 控制台"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "访问：https://dashboard.cpolar.com/"
echo "登录后查看'在线隧道'"
echo ""
echo "========================================="
echo ""
echo "💡 提示："
echo "  • 公网地址格式：https://xxxxx.cpolar.cn"
echo "  • 访客无需任何密码，直接访问即可"
echo "  • 分享给任何人都可以直接浏览"
echo ""
echo "🚀 获取地址后，立即分享给朋友测试吧！"
echo ""
